book = str(input('Podaj tytuł ksiązki? '))
name = str(input('Nazwisko autora '))
pages =int(input('Liczba stron '))
print(book.title())
print(name.title())
print(pages)
txt = 'book'
" ".join("book")
print(" ".join(txt))
print(len(txt))